### ISSUE TITLE
Hide more stuff

### ISSUE THREAD

**Issue by ckaran** [cberner/raptorq#29]
Just about everything in the crate has been declared `pub`, but I'm not sure if it really needs to be.  If there are portions that should only be visible within the crate, then the proper marker is `pub(crate)`.  That will reduce the amount of code that is required to be kept fixed and public.  Note that if you make anything non-public that was public, then you'll need to bump the major version number as it is a breaking change.

**Comment by cberner** [comment]
Very little of the crate is exposed from lib.rs, so the remaining `pub` structs aren't actually public. Feel free to submit a PR to change things from pub to pub(crate) though

**Comment by ckaran** [comment]
Will do, but I'm not too sure when I'll get to this.  I'm super busy at work right now, but if I get a few moments, I'll send PRs your way.

**Comment by ekmett** [comment]
As a devil's advocate: my attempts to use the library in practice have required me to go the opposite direction.

The existing open access to the block encoders/decoders is quite useful if you want to use them as black boxes for small quantities of data transmission (much like libRaptorq's "Raw" API). I've also needed to open up more stuff to be able to do things like read the number of bytes in an OTI description so the receiver can preemptively mmap the output file, without waiting to the end, possibly writing blocks into it as it goes, or ask how many blocks have been transmitted so far so I can update a status bar.

**Comment by ckaran** [comment]
@ekmett Do you have a complete list of what you'd want in a public API? Do you need **everything** that is currently exposed?

**Comment by ekmett** [comment]
I honestly don't know. Let's go through and see:

* `EncodingPacket` is there so you can serialize/deserialize data. The ability it has to split off payload ids can be useful if you're identifying the packet at a higher level of transport. That makes the entire API useful. `PayloadId` tells you which symbol and source block you have. If you are going to reassemble data on a target machine and have limited working memory these can be used to dump them out into a bin until you have enough to work with for the block. (I do need to send more data than will fit into main memory for instance.)

* `Decoder` provide the machinery for actually receiving anything according to the RFC. I would like to see additional hooks to get at how many blocks have been successfully transmitted so far in the decoder. Arguably this could be made a bit more efficient by keeping track of a count down timer in the decoder, rather than doing a linear scan for every packet. So that is one minor addition, but the 4 methods exposed on decoding are all important. I just want 1-2 more. Fortunately this is a thin enough wrapper around the `SourceDecoderBlock`s, that any shortcomings in this API can be made up in user code in a pinch, as long as those remain exposed.

* `Encoder` provides the machinery for actually packaging anything according to the RFC. `with_defaults` is the only hook you have to construct it, `get_config` gets the `ObjectTransmissionInformation` you need to send to the client for decoding, `get_encoded_packets` gives a sort of one stop API for getting an initial non-fountain-like batch of packets grouped by block, which is nice if you're replacing some Reed-Solomon-like code. `get_block_encoders` gives you access to the individual block encoders, which can be important if you need to fountain more packets to the user. That freedom is necessary if you want to shuffle blocks before transmission to avoid periodic drop issues, or if you want to use a non-systematic encoding. (say you have 50 machines all trying to seed the same file, the systematic approach from `get_encoded_packets` is then actively harmful.) That leaves that entire API required.

* `ObjectTransmissionInformation` provides you with the metadata about the packets you're sending, which is sent out of band or with every packet to set up the decoder depending on the usecase. It is a dumb struct, so hiding its guts is actively harmful in the event you need to transmit part of it at a higher layer. You can use the information provided by it to reconstitute the amount of working memory that the client would need to have in order to reassemble the given data for instance.

* The `SourceBlockEncoder` and `SourceBlockDecoder` structs provide more or less the equivalent to `libRaptorq`s "raw" API. Basically if you want to strip off the fairly simple Encoder/Decoder wrapper, they provide you with what you need in order to assemble symbols where you manage your own concept of blocks.

I'm actually left with a use for literally every public method that I can access from the crate.

* Most users will be able to get by with `Encoder`/`Decoder`/`EncodingPacket` and `ObjectTransmissionInformation`.

* Anybody using this for a data fountain or in a non-systematic multiple broadcaster situation will need access to the `SourceBlockEncoder`s to send ranges of repair packets. 

* Anybody resource constrained will need to use the information in the packets and bin things up for their own wrapper around `SourceBlockDecoder`s. This can also be used to decrease the target memory footprint further by letting you mmap and write out the data directly into the target file the moment a given block is complete, which can't be done through the surface level API.

So surprisingly, after doing a complete audit, I actually *do* need basically everything exposed by the current API.

I understand encapsulation as well as the next person, but I don't currently see huge swathes of internal state exposed here that isn't at least needed for at least one reasonable use-case.

As for other stuff that might be useful, I don't currently need but could at least see a use-case for access to a number of the magic constant tables from the RFC for computing things like required memory footprints for different file sizes.

There is a ton of stuff in the crate marked `pub`, but AFAICT, outside of the above list, none of it is actually exposed through any `pub` modules.

Turning this around, what concretely would you want to hide that is currently exposed?

**Comment by ckaran** [comment]
Not hide *per se*, but make it clear that some of this is really intended for internal consumption only.  If you can only access the stuff from within the crate (because it isn't directly exposed to the outside world), then making it 'pub(crate)' is a nice cleanliness step.  It also makes it a little easier to figure out what bits of code you can and can't use, which is the other reason I'm suggesting it.

**Comment by cberner** [comment]
Closing, but feel free to submit PRs to mark already internal code as `pub (crate)`

**Comment by ckaran** [comment]
OK, thank you.
